services:
    database:
        container_name: database
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - database_data:/var/lib/postgresql/data/ 

    azurite:
        container_name: azurite
        restart: unless-stopped
        command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck --loose
        ports:
            - 10000:10000
            - 10001:10001
            - 10002:10002
        volumes:
            - azurite_data:/data

    webapi.presentation:
        container_name: webapi-presentation
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
        ports:
          - "5001:8080"
          - "6001:8081"
        depends_on:
          - database
          - azurite

    runner.presentation:
        container_name: runner-presentation
        environment:
            - AzureWebJobsStorage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
            - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
        ports:
          - "7071:8080"
        depends_on:
          - database
          - azurite
