services:
    database:
        image: postgres:latest

    azurite:
        image: mcr.microsoft.com/azure-storage/azurite:latest

    webapi.presentation:
        image: ${DOCKER_REGISTRY-}webapipresentation
        build:
            context: .
            dockerfile: Src/Services/WebApi/WebApi.Presentation/Dockerfile

    runner.presentation:
        image: ${DOCKER_REGISTRY-}runnerpresentation
        build:
            context: .
            dockerfile: Src/Services/Runner/Runner.Presentation/Dockerfile

volumes:
    database_data:
    azurite_data:
